# Generated by Django 2.2.7 on 2020-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_key_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=64)),
                ('in_use', models.BooleanField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
